export const RECEIVED_APPDATA = 'RECEIVED_APPDATA';
export const SELECTING_PROJECT = 'SELECTING_PROJECT';
export const SELECTED_PROJECT = 'SELECTED_PROJECT';
export const EDITING_PROJECT = 'EDITING_PROJECT';
export const POSTING_PROJECT = 'POSTING_PROJECT';
export const POSTED_PROJECT = 'POSTED_PROJECT';
