export const RECEIVED_APPDATA = 'RECEIVED_APPDATA';
export const SELECTING_PROJECT = 'SELECTING_PROJECT';
export const SELECTED_PROJECT = 'SELECTED_PROJECT';
export const EDITING_PROJECT = 'EDITING_PROJECT';
export const UPDATED_PROJECT = 'UPDATED_PROJECT';
